name: e_shop
description: Flutter eCommerce App using Firebase Firestore from Coding Cafe

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.13.2+1
  firebase_auth: ^0.16.1
  shared_preferences: ^0.5.6+1
  fluttertoast: ^3.1.3
  firebase_storage: ^3.1.1
  flutter_staggered_grid_view: ^0.3.0
  provider: ^4.0.4
  path_provider: ^1.4.0
  image: ^2.0.7
  image_picker: ^0.6.7+14
  location: ^3.0.0
  geocoder: ^0.2.1
  geolocator: ^6.1.10
  google_sign_in: ^4.0.2
  font_awesome_flutter: ^8.10.0
  carousel_pro: ^1.0.0
  google_maps_flutter: ^0.5.30
  url_launcher: ^5.0.3
  get_it: ^1.0.3+2
  autocomplete_textfield: ^1.7.3
  http: ^0.12.1
  animations: ^1.1.2
  intl: ^0.16.1
  lottie: ^0.6.0
  google_fonts: ^1.1.0
  lit_firebase_auth: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf

  assets:
    - images/welcome.png
    - images/login.png
    - images/admin.png
    - images/cash.png
    - images/1.png
    - images/google.png
    - images/2.png
    - assets/lottie/


